### PR TITLE
fixing errors on new loan page

### PR DESCRIPTION
**Pull request by rszaloki**
#### Is connection necessary to test? If so which network?
- [ ] local RPC
- [ ] Rinkeby
- [ ] Main Ethereum Network

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Building with commit 03c96a699eb2bf0e84a7755ccb207b9f87d6ae78

https://app.netlify.com/sites/augmint/deploys/5ca764b543a6cd0008182966

**Comment by rszaloki** [comment]
Yeah, thats another problem with the webserver's config: it cannot comprehend urls with two slashes :( eg: /loan/new or /lock/new)

**Comment by szerintedmi** [comment]
> Yeah, thats another problem with the webserver's config: it cannot comprehend urls with two slashes :( eg: /loan/new or /lock/new)

It used to be working. Something has changed somewhere.

**Comment by szerintedmi** [comment]
> > Yeah, thats another problem with the webserver's config: it cannot comprehend urls with two slashes :( eg: /loan/new or /lock/new)
> 
> It used to be working. Something has changed somewhere.

it seems to be an unrelated issue, /account works, /account/ doesn't on deployment.

**Comment by rszaloki** [comment]
Hmm, strange :( I can't find any errors before this commit. There were two errors:
- React complained about key collision on the list items (this is fixed with the `key={product.id}`
- React also complained about the `for` attribute

However, today I checked the staging before this branch and I can't reproduce it either. Should I close it?

**Comment by szerintedmi** [comment]
@rszaloki  : shall we merge or close that ? I already approved but you suggest we should just close

**Pull request merged**
