### PR TITLE
New dashboard layout

### PR DESCRIPTION
**Pull request by szerintedmi**

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Built with commit b1845a6dcdb1b309382f811d1b77a08c42203778

https://app.netlify.com/sites/augmint/deploys/5b03e43e11b73b33deba986d

**Comment by reyrodrigez** [comment]
@Augmint/frontend this is ready for review: https://deploy-preview-221--augmint.netlify.com/account?f_dashboard=true .
I've fixed some of the issues from [trello](https://trello.com/b/EaLEaHCK/sitebuild) but there are still plenty. If you find something please raise a ticket and add the `dashboard` label.

**Comment by szerintedmi** [comment]
It's fine to have issues with the dasahboard as it's behind a feature toggle. The primary goal is to merge the codebase to staging as it will be bigger and bigger pain by time.
What we must test if the branch works with the dashboard toggle OFF. I found some issues, will create trello cards

**Comment by szerintedmi** [comment]
I clicked through all the functions with dashboard feature toggle OFF - seems to work. So it's good to merge, we will keep testing and fixing dashboard with toggle. (I can't approve this as I opened it, @gyurka00  ? )

**Pull request merged**
