### PR TITLE
Margin loan

### PR DESCRIPTION
**Pull request by rszaloki**
WIP!

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Building with commit ce5aa609858a1ca44729e2be99c672657cd67095

https://app.netlify.com/sites/augmint/deploys/5d3703ac1f7160000824ac0c

**Comment by szerintedmi** [comment]
I would review it but build failed:
```
error Couldn't find any versions for "@augmint/js" that matches "0.3.4"
```

**Comment by szerintedmi** [comment]
when / why did it became read despite it's far from due?
image

**Comment by szerintedmi** [comment]
some collateralisation info should be added.
Maybe % ? And a big warning if it's below a threshold? (that warning should go to my account page too?) @krosza ? @phraktle ?
image

**Comment by phraktle** [comment]
> some collateralisation info should be added.
> Maybe % ? And a big warning if it's below a threshold? (that warning should go to my account page too?)

Yes, discussed this today, we’ll ad a large box with collateralization level (and margin call rate) that turns red with a warning (similar to sue date).

**Comment by szerintedmi** [comment]
stability report on mainnet, legacy loans sum seems to be wrong (unfortunately :) ). 
image

**Comment by krosza** [comment]
collateralisation and rate  info to be included:  ( besides
collateralization level!)
- margin call eth rate    besides the actual eth rate on the loan page
- warning at the upper bar  if  difference between margin call eth rate and
actual eth rate less than (5)% point


Q: there will not be partial repayment?
Q: what is the purpose of MARGIN LOAN button?

**Comment by krosza** [comment]
Stability Report has some serious issue:

It does not reveal the real solvency of Augmint. the problem that after
collection if there was no immediate aeur buy of the collected loan amount
the system quickly can became insolvent. This is the case now, because the
actual eth rate lower than the collection eth rate was. Ergo there is no
enough eth in the market intervention reserve to buy the appropriate amount
of aeur.
Even worse that it is quite complicated to  figure out the actual missig
eth amount. or the aeur supply without cover.

The uncovered aeur amount = Loans Collected- A-EUR Market Intervention
Reserve - ETH Market Intervention Reserve*actual eth rate
if it is a negative amount, that means profit to be realized.

**Comment by phraktle** [comment]
@szerintedmi @krosza Stability Report bug was fixed. For other issues related to Stability Report, please open a separate ticket since it's not related to margin loans.

Loan card was updated as follows.

Normal state:
Screen Shot 2019-08-02 at 17 22 50

Margin call warning state:
Screen Shot 2019-08-02 at 17 23 26

**Pull request merged**
