### PR TITLE
Improve top nav and account overview layout

### LINKED ISSUE #623: Balance decimals on account page shown without trailing 0
should be formatted as everywhere else
image

also wrong in dropdown shown from topnav 
image

### LINKED ISSUE #624: A€ symbol for total loan / lock amount is breaking to new line on my account page
image

image

### PR DESCRIPTION
**Pull request by admrid**
#### Trello card / screenshot / wireframe link:
- add currency tags
- fix mobile view
- add minor style changes for better visibility/readability
- add acc address & copy feature to the balance module @ /account
- and:
fixes #623 
fixes #624

#### Is connection necessary to test? If so which network?
- [ ] local RPC
- [x] Rinkeby
- [ ] Main Ethereum Network

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Building with commit 9497b678365aac5d07b68a7669a6c5ea27be258a

https://app.netlify.com/sites/augmint/deploys/5cda8f22b1b43300097ace8e

**Comment by admrid** [comment]
> * [ ]  too many decimal zeros in ETH balance
>   image
> * [ ]  horizontal scroll in my account history on 320px
>   image
> * [ ]  My total loans and total locks is breaking into two lines too early
>   image

these are not really about the accountInfo comp. 
and i am anyway refreshing the /account page so let's push them to that PR.
(there is tho one small fix coming related to the accInfo comp)

**Comment by szerintedmi** [comment]
> these are not really about the accountInfo comp.
> and i am anyway refreshing the /account page so let's push them to that PR.
> (there is tho one small fix coming related to the accInfo comp)

Right, moved to https://github.com/Augmint/augmint-web/issues/657

**Comment by admrid** [comment]
@phraktle 
i think this can be merged now.
all the other points of yours are going to be addressed in another PR

**Comment by phraktle** [comment]
@admrid is the design change making the upper right panel white instead of the previous yellow intentional or a bug?

**Comment by admrid** [comment]
@phraktle 
intentional:
i think for now it is good to have those pieces of information presented there,
but those should not take the focus off from the main content/actions of the app,
hence there is no need for those to be visually this strong.

**Pull request merged**
