### PR TITLE
fix(tryit): change colors

### PR DESCRIPTION
**Pull request by gyurka00**

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Built with commit 08465dba373d39e5f3561596b8e968b6e0290da2

https://app.netlify.com/sites/augmint/deploys/5b20d71c0733d50b09855f09

**Comment by admrid** [comment]
@szerintedmi 
ic, i forgot about the `without metamask` version if that's what you meant

**Comment by szerintedmi** [comment]
@admrid : that's one of the issues. the other one is the "normal" try it - it still has some white on white 
image

**Comment by szerintedmi** [comment]
This is the one when no metamask:
image

**Comment by admrid** [comment]
@szerintedmi youthinkwe are good? (i think we are good)

**Pull request merged**
