### PR TITLE
Greenkeeper/styled components 4.1.1

### PR DESCRIPTION
**Pull request by szerintedmi**
#### Is connection necessary to test? If so which network?
- [ ] local RPC
- [ ] Rinkeby
- [ ] Main Ethereum Network

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Built with commit 29bcb0b63aa2bbd28fbcbc7e45d92b6783e8a993

https://app.netlify.com/sites/augmint/deploys/5bec485941174f189dfaf96e

**Comment by admrid** [comment]
I think I've done what I had to do...:
- What do I need to do to migrate to v4?
https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4

**Comment by admrid** [comment]
for some reason there is a `noScroll` bug in this PR but that is fixed in #459

**Comment by reyrodrigez** [comment]
That seems to be it as per the migration guide.
One specific issue could come up with `semantic-ui`:
both `styled-components` and `sematic-ui` uses the `as` prop and neither of them pass it down to the child component assuming it's part of their own API.
Let's have throughout look on staging if all the elements are rendered correctly since the issue could not be caught by cypress.

**Pull request merged**
