### PR TITLE
[feedback] first step

### PR DESCRIPTION
**Pull request by gyurka00**
add survicate feedback

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Built with commit eb82807b13341ac05bf18a2b865a6809cd118a89

https://app.netlify.com/sites/augmint/deploys/5b07c44a11b73b187940b280

**Comment by reyrodrigez** [comment]
@gyurka00 @szerintedmi is there a trello card for this?

**Comment by reyrodrigez** [comment]
@gyurka00 @szerintedmi what's the status of this one? is there a ticket?

**Comment by gyurka00** [comment]
This is the ticket:
https://trello.com/c/0diwK9od/139-add-feedback-popup-for-the-pilot

**Comment by phraktle** [comment]
closing as obsolete.

**Pull request closed without merging**
